-- MySQL Script generated by MySQL Workbench
-- 10/27/17 17:37:24
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema en2ch
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema en2ch
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `en2ch` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `en2ch` ;

-- -----------------------------------------------------
-- Table `en2ch`.`sm_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `en2ch`.`sm_user` (
  `id` CHAR(36) NOT NULL,
  `username` VARCHAR(24) NOT NULL,
  `cn_name` VARCHAR(6) NULL,
  `en_name` VARCHAR(24) NULL,
  `birthday` DATETIME NULL,
  `created_time` DATETIME NOT NULL,
  `created_by` CHAR(36) NOT NULL,
  `modified_time` TIMESTAMP NOT NULL,
  `modified_by` CHAR(36) NOT NULL,
  `is_deleted` BIT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_id` (`id` ASC),
  UNIQUE INDEX `uk_username` (`username` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
